name: Generate and Deploy Live File

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 */2 * *'  # Runs every 2 days at midnight
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

        run: |
          cd Tv_search
          python search_Tv.py

      - name: Commit and push live.txt to the repository
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Actions"
          git add live.txt
          git commit -m "Updated live.txt with new data"
          git push  # 推送到当前分支，GitHub pages应当配置为基于这个分支来发布网站

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3  # 使用第三方动作来部署GitHub Pages
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  # 使用GitHub提供的token进行权限认证
          publish_dir: ./  # live.txt的目录，这应当与生成该文件的目录相对应
