name: Run Python Script and Deploy Live Text File

on:
  workflow_dispatch:

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  

    - name: Run Python Script
      run: |
        cd Tv_search
        python search_Tv.py

    # 假设您的脚本已经生成了 live.txt 文件，
    # 下面的步骤将这个文件提交到一个分支（通常是 gh-pages）。
    - name: Commit live.txt File
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Actions"
        git add Tv_search/live.txt
        git commit -m "Update live.txt" -a || echo "No changes to commit."
        # 这将把修改推送到gh-pages分支，这个分支会被GitHub Pages用来发布内容。
        git push origin HEAD:gh-pages

    # 这个步骤用于部署到GitHub Pages。
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        keep_files: true  # 保留已存在的文件
        publish_dir: ./Tv_search/  # 在这个目录下搜索 live.txt 文件
